### ISSUE TITLE
de-stephenize the scripts

### ISSUE THREAD

**Issue by pdehaye** [sftcd/tek_transparency#1]
The scripts make heavy reference to `/home/stephen/code/tek_transparency`. This should probably go away  ;-)

**Comment by sftcd** [comment]
On 02/07/2020 21:50, pdehaye wrote:
> The scripts make heavy reference to
> `/home/stephen/code/tek_transparency`. This should probably go away
> ;-)

Yeah, fair point. Makes running a cron job easier
for me, but will fix.

S.

>

**Comment by sftcd** [comment]
Attempted fix in this [commit](https://github.com/sftcd/tek_transparency/commit/9e9c536517cf62961523a99be438249528ae2584) - vars will be taken from environment if set or default to what works for me, if you wanna run a cron job with other vars, you'll need to set HOME etc explicitly in your crontab (exactly HOWTO depends on which version of cron apparently).

**Comment by pdehaye** [comment]
Thank you!

**Comment by pdehaye** [comment]
What is this doing on your system? 

`date -d "00:00:00Z" +%s`

I am trying to find the same option on mine.
