### ISSUE TITLE
Change endpoint for Netherlands app

### ISSUE THREAD

**Issue by damaarten** [sftcd/tek_transparency#16]
Hi, I am on the team of the Dutch app.
We switched from endpoint https://productie.coronamelder-dist.nl/v1 to https://productie.coronamelder-dist.nl/v2. The only difference is a new TLS certificate. Other than that the new endpoint is exactly the same.
We are phasing out the v1 endpoint end of October, that is why I am requesting this change.
So could you change line 2006 of tek_survey.sh to `NL_BASE="https://productie.coronamelder-dist.nl/v2"`.
You can also remove lines 2145 and 2146 `# don't appear to be too keen:-); sleep 1` since the files are served from a CDN and your hourly download does not hurt at all.

**Comment by sftcd** [comment]
Hiya,

On 23/10/2020 00:22, damaarten wrote:
> Hi, I am on the team of the Dutch app. We switched from endpoint
> https://productie.coronamelder-dist.nl/v1 to
> https://productie.coronamelder-dist.nl/v2. The only difference is a
> new TLS certificate. Other than that the new endpoint is exactly the
> same. We are phasing out the v1 endpoint end of October, that is why
> I am requesting this change. So could you change line 2006 of
> tek_survey.sh to
> `NL_BASE="https://productie.coronamelder-dist.nl/v2"`. You can also
> remove lines 2145 and 2146 `# don't appear to be too keen:-); sleep
> 1` since the files are served from a CDN and your hourly download
> does not hurt at all.
> 

Many thanks! Will make that change tomorrow.

Cheers,
S.

**Comment by sftcd** [comment]
Made that change. Thanks again.
