### ISSUE TITLE
Bug in defining midnights in CH script

### ISSUE THREAD

**Issue by pdehaye** [sftcd/tek_transparency#3]
This line is unfortunately problematic:
https://github.com/sftcd/tek_transparency/blob/d284dff907a844bbe227f288bd938a3f017de961/tek_survey.sh#L340
It means on day X it will download the CH bundles of days X, X-1, X-(1+2), X-(1+2+3), etc.

**Comment by sftcd** [comment]
Ah crap yeah, think that's wrong all right. Testing a fix locally for a sec. Thanks!

**Comment by sftcd** [comment]
Looks like that may have sorted it.
