### ISSUE TITLE
Scraping suggestion

### ISSUE THREAD

**Issue by pdehaye** [sftcd/tek_transparency#6]
This official website from CH offers two tidbits of interesting information, worth scraping:
https://www.experimental.bfs.admin.ch/expstat/en/home/innovative-methods/swisscovid-app-monitoring.html

* the app activation user base;
* a sentence changing daily: "On 13 July, 5 users of the SwissCovid app entered a Covid code in their app. During the seven days between 7 and 13 July, a total of 63 Covid codes were therefore entered."

It would be worth scraping both, especially the second one.

**Comment by sftcd** [comment]
On 15/07/2020 20:42, pdehaye wrote:
> This official website from CH offers two tidbits of interesting information, worth scraping:
> https://www.experimental.bfs.admin.ch/expstat/en/home/innovative-methods/swisscovid-app-monitoring.html
> 
> * the app activation user base;
> * a sentence changing daily: "On 13 July, 5 users of the SwissCovid app entered a Covid code in their app. During the seven days between 7 and 13 July, a total of 63 Covid codes were therefore entered."
> 
> It would be worth scraping both, especially the second one. 

Fine idea. Will add.

S.


>

**Comment by sftcd** [comment]
Added those. They're collected now for each run but not displayed.
